server:
        servlet:
                context-path: /api
        port: 8888

spring:
        datasource:
                url: jdbc:postgresql://121.36.222.1:5432/daily?currentSchema=daily
                username: gaussdb
                password: Group7pwd@
                driverClassName: org.postgresql.Driver

mybatis:
        mapper-locations: classpath:mapping/daily/*.xml
        type-aliases-package: com.daily.model.entity

ENCODE_KEY: <YOUR ENCODE KEY HERE>

logging:
        level:
                com.daily: debug