server:
        servlet:
                context-path: /api
        port: 8888

spring:
        datasource:
                driver-class-name: com.mysql.cj.jdbc.Driver
                username: root
                password: wql011213
#                url: jdbc:mysql://124.222.109.34:3306/daily_db?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
                url: jdbc:mysql://localhost:3306/daily_db?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false

mybatis:
        mapper-locations: classpath:mapping/*.xml
        type-aliases-package: com.daily.model.entity

ENCODE_KEY: <YOUR ENCODE KEY HERE>

logging:
        level:
                com.daily: debug